### ISSUE TITLE
Problem with compiler optimization

### ISSUE THREAD

**Issue by hbjusa** [jmhodges/kdtree2#1]
When this code is compiled with optimization on, the Fortran module can consistently return incorrect results, at least with certain compilers on certain systems. It apparently stems from the use of the instance 'sr' of the derived type tree_search_record declared on line 603 of kdtree2.f90

```
  type(tree_search_record), save, target :: sr   ! A GLOBAL VARIABLE for search
```

where the global variable sr is then used in various routines.  It looks like compiler optimization of code can result in vectorization of loops causing values in sr to be overwritten in memory.  The result is incorrect values being returned to the calling routine.  This should be fairly easy to fix, but it will be fairly invasive.  I am happy to contribute, but I wonder if there is anybody else interested in maintaining this code?

**Comment by jmhodges** [comment]
Sorry, I'm unfamiliar with the Fortran code. You'll want to talk to the original authors. I've just posted it here because I was working on it a few years ago.

**Comment by hbjusa** [comment]
Haven't been able to find a valid current email for the author, so may try to make the changes myself and submit them.

**Comment by jmhodges** [comment]
This repo is going to be archived, and the author is elsewhere, so
