### ISSUE TITLE
Boost multiarray reports invalid index when constructing kd tree

### ISSUE THREAD

**Issue by feiyuren233** [jmhodges/kdtree2#3]
I got an error saying an index was invalid when build_for_range is being called recursively, anyone know what's the possible reason? 
Because I saw the last 2 calls to build_for_range has the same parameter, is this suppose to happen? or my source data is corrupted?
Thanks in advance.

**Comment by jmhodges** [comment]
Sorry, I've not played with this code in a long time and this repo is being archived.
