### ISSUE TITLE
Error in Vector3.LargestAxis() 		{

### ISSUE THREAD

**Issue by edgar005** [jmhodges/kdtree2#4]
Hi
for negative values of Vector3 coordinate values there is an error in Vector3.LargestAxis()  
Instead of comparing the values of X,Y,Z, you should compare the absolute values.

**Comment by hbjusa** [comment]
I'm trying to find this in the C++ code so that I can determine whether the Fortran version has a similar issue.  However, I can't seem to find the string 'Vector3.LargestAxis'.  Can you please tell where the error occurs?

**Comment by hbjusa** [comment]
I don't think the Fortran implementation has the same problem.

**Comment by edgar005** [comment]
Hi
please accept my appologies! I posted the error in the false project, which is also named kdtree2. the one where this error occurs is: https://github.com/Jerdak/KDTree2
sorry again!

**Comment by hbjusa** [comment]
Thank you for taking the time to respond!

H
